### ISSUE TITLE
Executables.

### ISSUE THREAD

**Issue by VietnamecDevelopment** [michalvankodev/metaframer#3]
Hello Michal,

Can u please make this an executable? like curl | sh setup for linux and .exe for windows.. because not everyone has Rust installed and installing Rust in windows is pain in the ass.

Thanks, Vietnamec.

**Comment by michalvankodev** [comment]
Hi @VietnamecDevelopment,

This is on the roadmap for sure. However, I will need some help with testing Windows executables as I don't own a Windows computer/license.

metaframer requires an installation process instead of just uploading an executable. It depends on user-defined templates, which are stored in the user's .config folder. I have no idea what the equivalent of it is on Windows.

**Comment by VietnamecDevelopment** [comment]
i can test it as i own a windows pc.. but we could look at the .config together if xou want
